# Generated by Django 3.2.25 on 2025-10-15 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlReinicio',
            fields=[
                ('reset_id', models.AutoField(db_column='resetId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Control de Reinicio',
                'verbose_name_plural': 'Controles de Reinicio',
                'db_table': 'Control_Reinicio',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_id', models.AutoField(db_column='moduloId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=5, null=True)),
                ('version', models.CharField(choices=[('1.0', '1.0'), ('2.0', '2.0')], default='1.0', max_length=3)),
                ('up', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)])),
                ('down', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)])),
                ('reset', models.ForeignKey(blank=True, db_column='resetId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos', to='modulos.controlreinicio')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('medicion_id', models.AutoField(db_column='medicionId', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_press', models.CharField(blank=True, max_length=100, null=True)),
                ('modulo', models.ForeignKey(db_column='moduloId', on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='modulos.modulo')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'db_table': 'Mediciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogReinicio',
            fields=[
                ('log_reset_id', models.AutoField(db_column='logResetId', primary_key=True, serialize=False)),
                ('reinicio', models.SmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reset', models.ForeignKey(db_column='resetId', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='modulos.controlreinicio')),
            ],
            options={
                'verbose_name': 'Log de Reinicio',
                'verbose_name_plural': 'Logs de Reinicios',
                'db_table': 'Log_Reinicios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InfoModulo',
            fields=[
                ('info_id', models.AutoField(db_column='infoId', primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('version_firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('uptime', models.IntegerField(blank=True, help_text='Segundos', null=True)),
                ('memoria_libre', models.IntegerField(blank=True, help_text='Bytes', null=True)),
                ('temperatura_interna', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('voltaje_alimentacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='dBm', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(db_column='moduloId', on_delete=django.db.models.deletion.CASCADE, related_name='info_tecnica', to='modulos.modulo')),
            ],
            options={
                'verbose_name': 'Información de Módulo',
                'verbose_name_plural': 'Información de Módulos',
                'db_table': 'Info_Modulo',
            },
        ),
        migrations.CreateModel(
            name='EstadoConexion',
            fields=[
                ('estado_id', models.AutoField(db_column='estadoId', primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('TIMEOUT', 'Timeout'), ('RECONEXION', 'Reconexión')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_desconexion', models.IntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('modulo', models.ForeignKey(db_column='moduloId', on_delete=django.db.models.deletion.CASCADE, related_name='estados_conexion', to='modulos.modulo')),
            ],
            options={
                'verbose_name': 'Estado de Conexión',
                'verbose_name_plural': 'Estados de Conexión',
                'db_table': 'Estado_Conexion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='controlreinicio',
            name='modulo',
            field=models.ForeignKey(blank=True, db_column='moduloId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_reinicio', to='modulos.modulo'),
        ),
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('beam_id', models.AutoField(db_column='beamId', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_up', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)])),
                ('valor_down', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.5)])),
                ('modulo', models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='apuntes', to='modulos.modulo')),
            ],
            options={
                'verbose_name': 'Apunte',
                'verbose_name_plural': 'Apuntes',
                'db_table': 'Beam',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='infomodulo',
            index=models.Index(fields=['modulo', 'fecha_actualizacion'], name='Info_Modulo_moduloI_11c84f_idx'),
        ),
        migrations.AddIndex(
            model_name='estadoconexion',
            index=models.Index(fields=['modulo', 'fecha'], name='Estado_Cone_moduloI_9881b0_idx'),
        ),
        migrations.AddIndex(
            model_name='estadoconexion',
            index=models.Index(fields=['tipo_evento'], name='Estado_Cone_tipo_ev_8b80c3_idx'),
        ),
    ]
