# Generated by Django 3.2.23 on 2025-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_auto_20251020_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='direccion_mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='memoria_libre',
            field=models.IntegerField(blank=True, help_text='En bytes', null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='temperatura_interna',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='version_firmware',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='voltaje_alimentacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
