# Generated by Django 3.2.23 on 2025-10-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_auto_20251023_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlreinicio',
            name='estado',
            field=models.BooleanField(default=False, help_text='True=Encendido, False=Apagado'),
        ),
    ]
